### PR TITLE
Added API call for bootstrapping node

### PR DESCRIPTION
**Pull request by QuickMythril**
Works like the "admin/restart" API call, but also deletes the folder specified in the repositoryPath setting.

Related commit:
https://github.com/Qortal/qortal/commit/7bb6b84e86dae04fe1ca1eebbd8385660d8a0ba0 - Added API call for restarting node

### CODE REVIEW

**Comment by AlphaX-Projects** [comment]
What is the reason to have a double api call for bootstrap ?
As i know we have one here
https://github.com/Qortal/qortal/blob/master/src/main/java/org/qortal/api/restricted/resource/BootstrapResource.java

**Comment by AlphaX-Projects** [comment]
Ok just saw it is to do it from the ui, sorry.
Is it tested on all systems ? Like win macos lin etc ?

**Comment by AlphaX-Projects** [comment]
@QuickMythril you can fast replay on other PR but on your own not ?
I asked if the PR is tested on all main systems , if yes i can merge this.

**Comment by QuickMythril** [comment]
i have tested, but i think it would be good for others to test as well.

**Comment by AlphaX-Projects** [comment]
> i have tested, but i think it would be good for others to test as well.

from tomorrow i have vecation so will test then on my machines.

**Pull request merged**
