### PR TITLE
Initial (almost) phase-1 Reticulum implementation

### PR DESCRIPTION
**Pull request by jschulthess**
This marks the initial PR to the "reticulum" branch.

The code is the start and almost phase-1 implementation of the alternative networking for Qortal based on Reticulum.
It uses the Java implementation of Reticulum [reticulum-network-stack](https://github.com/sergst83/reticulum-network-stack).
At present the Reticulum network stack runs alongside the native network stack without interfering with any of the Qortal functionality.

Note: The code is a new branch created today from a freshly synced "master" branch. The "reticulum" branch was created a few months ago. Therefore most of the files being changed are updates representing the current master branch as of today (20240424).

### CODE REVIEW

**Comment by QuickMythril** [comment]
I'm not sure why all the commits from v4.4.0 and prior are included in this preview, but to see exactly what changes are being added from the reticulum branch, it is easier to compare against the master branch:

https://github.com/Qortal/qortal/compare/master...jschulthess:qortal:reticulum
`1 commit, 10 changed files, 883 additions`

**Comment by QuickMythril** [comment]
Possible filename typo (should be Network, not Networ?):
`src/test/java/org/qortal/test/network/RNSNetworTest.java`

**Comment by jschulthess** [comment]
> Possible filename typo (should be Network, not Networ?): `src/test/java/org/qortal/test/network/RNSNetworTest.java`

Fixed the file name. Shows how much time I spent on the testing code ;-)

**Comment by jschulthess** [comment]
> I'm not sure why all the commits from v4.4.0 and prior are included in this preview, but to see exactly what changes are being added from the reticulum branch, it is easier to compare against the master branch:
> 
> [master...jschulthess:qortal:reticulum](https://github.com/Qortal/qortal/compare/master...jschulthess:qortal:reticulum) `1 commit, 10 changed files, 883 additions`

The pull request creation did that automatically. I guess it is because the branch "reticulum" was created a few months ago and therefore a number of commits behind while I had a version that is in sync with the current master branch.

**Comment by crowetic** [comment]
since this is on another branch there shouldn't be any issue merging.

**Pull request merged**
