### PR TITLE
feat: add Dockerfile

### PR DESCRIPTION
**Pull request by otaku**
Add Docker support.

Assuming it takes less then 5 minutes before the API is booted and listening for the health check.

`settings.json` will have to be placed in the volume.

Qortal data directory is at `/qortal`

### CODE REVIEW

**Comment by EarthTek** [comment]
Very nice! Thanks for adding this! IMO docker is a win for Qortal.

**Comment by otaku** [comment]
I've used the `log4j2.properties` located in the project but I feel it should be a one which logs to stdout instead.

**Comment by EarthTek** [comment]
Have you heard of Podman? Very curious to get your take on it? 
https://medium.com/technopanti/docker-vs-podman-c03359fabf77

**Comment by otaku** [comment]
I use both, the `Dockerfile` works with Podman as well.  There's also https://docs.docker.com/engine/security/rootless/  There's pros and cons for each.  Find me on Discord if you want to discuss this!

**Comment by EarthTek** [comment]
Most excellent, will do!

**Comment by CalDescent14** [comment]
Thanks for contributing this! It is now merged, although GitHub seems to have glitched and hasn't updated the status.

**Comment by JaymenChou** [comment]
> Add Docker support.
> 
> Assuming it takes less then 5 minutes before the API is booted and listening for the health check.
> 
> `settings.json` will have to be placed in the volume.
> 
> Qortal data directory is at `/qortal`

Placed settings.json in volume but still cant

**Pull request closed without merging**
